export enum LocalStorage {
  WORK_TYPE_STATUS = 'work-type-status',
  WORK_TYPE_PAGE = 'work-type-page',
  USER_STATUS = 'user-status',
  USER_ROLE = 'user-role',
  USER_PAGE = 'user-page',
  PROJECT_SEARCH_PAGE = 'project-search-page',
  PROJECT_FILTER_PAGE = 'project-filter-page',
  PROJECT_FILTER_IS_ENDED = 'project-filter-is-ended',
  PROJECT_FILTER_IS_NOT_ACCEPTANCE = 'project-filter-is-not-acceptance',
  PROJECT_FILTER_IS_LAST_IN_WORK = 'project-filter-is-last-in-work',
  PROJECT_FILTER_IS_CURRENT_IN_WORK = 'project-filter-is-current-in-work',
  PROJECT_FILTER_IS_CURRENT_PR_OVERDUE = 'project-filter-is-current-pr-overdue',
  PROJECT_FILTER_IS_CURRENT_OP_OVERDUE = 'project-filter-is-current-op-overdue',
  EMPLOYEE_STATUS = 'employee-status',
  EMPLOYEE_PAGE = 'employee-page',
  EMPLOYEE_TYPE_WORKS = 'employee-type-works',
  EMPLOYEE_MODIFIED_TYPE_WORKS = 'employee-modified-type-works',
  PROJECT_STATUS = 'project-status',
  NAVBAR_LIST = 'navbar-list',
  PROJECT_PAGE = 'project-page',
}
