export const Paths = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  CONSTRUCTORS: '/constructors',
  CONSTRUCTORS_CREATE: '/constructors/create',
  CONSTRUCTORS_EDITING: '/constructors/editing',
  EMPLOYEES: '/employees',
  EMPLOYEES_CREATE: '/employees/create',
  EMPLOYEES_EDITING: '/employees/editing',
  REPORTS: '/reports',
  WORK_TYPES: '/work-types',
  WORK_TYPES_CREATE: '/work-types/create',
  WORK_TYPES_EDITING: '/work-types/editing',
  MAIN: '/',
  PROJECT_STAGES: '/project/:id/stages',
  EMPLOYEE_LOGIN: '/employee-login',
  EMPLOYEE_MAIN: '/employee-main',
  EMPLOYEE_PROJECTS: '/employee-projects',
  EMPLOYEE_PROJECT_STAGES: '/employee/project/:id/stages',
  EMPLOYEE_STAGES_IN_WORK: '/employee-stages-in-work',
  STAGES_IN_WORK: '/stages-in-work',
};
