export const Paths = {
  LOGIN: '/login',
  MAIN: '/',
  SELECTION: '/selection',
  PROJECTS: '/projects',
  PROJECT_STAGES: '/project/:id/stages',
  EMPLOYEES: '/employees',
  EMPLOYEE_LOGIN: '/employee-login',
  EMPLOYEE_MAIN: '/employee-main',
  EMPLOYEE_PROJECTS: '/employee-projects',
  EMPLOYEE_PROJECT_STAGES: '/employee/project/:id/stages',
  EMPLOYEE_STAGES_IN_WORK: '/employee-stages-in-work',
  STAGES_IN_WORK: '/stages-in-work',
  TEST: '/test',
};
